version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  build-app:
    macos:
      xcode: "16.2.0"
    resource_class: macos.m1.medium.gen1

    environment:
      XCODE_PROJECT: amnesia.xcodeproj
      XCODE_SCHEME: amnesia
      XCODE_SDK: macosx
      XCODE_CONFIGURATION: Release
      DERIVED_DATA_PATH: build

    steps:
      - checkout

      - run:
          name: Show Xcode and Swift versions (Informational)
          command: |
            echo "Xcode Version:"
            xcrun xcodebuild -version
            echo "Swift Version:"
            xcrun swift -version

      - restore_cache:
          keys:
            - v1-swift-pm-{{ .Branch }}-{{ checksum "amnesia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
            - v1-swift-pm-{{ .Branch }}-
            - v1-swift-pm-

      - run:
          name: Resolve Swift Package Dependencies
          command: |
            if [ -f "amnesia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" ]; then
              xcodebuild -resolvePackageDependencies \
                         -project "$XCODE_PROJECT" \
                         -scheme "$XCODE_SCHEME" \
                         -derivedDataPath "$DERIVED_DATA_PATH"
            else
              echo "Package.resolved not found. The build step will attempt to resolve dependencies."
            fi

      - save_cache:
          key: v1-swift-pm-{{ .Branch }}-{{ checksum "amnesia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
          paths:
            - "$DERIVED_DATA_PATH/SourcePackages"

      - run:
          name: Build Application
          command: |
            xcodebuild -project "$XCODE_PROJECT" \
                       -scheme "$XCODE_SCHEME" \
                       -sdk "$XCODE_SDK" \
                       -configuration "$XCODE_CONFIGURATION" \
                       -derivedDataPath "$DERIVED_DATA_PATH" \
                       clean build \
                       CODE_SIGNING_ALLOWED=NO \
                       CODE_SIGN_IDENTITY="" \
                       PROVISIONING_PROFILE_SPECIFIER=""

      - store_artifacts:
          name: Store .app Bundle
          path: "$DERIVED_DATA_PATH/Build/Products/$XCODE_CONFIGURATION/amnesia.app"
          destination: amnesia.app

      - store_artifacts:
          name: Store Build Logs
          path: "$DERIVED_DATA_PATH/Logs/Build"
          destination: build-logs

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-app:
          filters:
            branches:
              only:
                - main
